### ISSUE TITLE
Unable to successfully deploy

### ISSUE THREAD

**Issue by Tarni-Baghel** [pankod/next-boilerplate#136]
I am trying to deploy it but getting following error:

> {
>     "errorType": "Error",
>     "errorMessage": "ENOENT: no such file or directory, scandir '/var/task/public/static/locales/en'",
>     "code": "ENOENT",
>     "errno": -2,
>     "syscall": "scandir",
>     "path": "/var/task/public/static/locales/en",
>     "stack": [
>         "Error: ENOENT: no such file or directory, scandir '/var/task/public/static/locales/en'",
>         "    at Object.readdirSync (fs.js:955:3)",
>         "    at getAllNamespaces (/var/task/pages/_error.js:24275:19)",
>         "    at createConfig (/var/task/pages/_error.js:24280:27)",
>         "    at new NextI18Next (/var/task/pages/_error.js:30962:48)",
>         "    at Object.kluC (/var/task/pages/_error.js:24933:29)",
>         "    at __webpack_require__ (/var/task/pages/_error.js:23:31)",
>         "    at Module.iJV/ (/var/task/pages/_error.js:23264:70)",
>         "    at __webpack_require__ (/var/task/pages/_error.js:23:31)",
>         "    at Module.5L4k (/var/task/pages/_error.js:4153:19)",
>         "    at __webpack_require__ (/var/task/pages/_error.js:23:31)"
>     ]
> } 

I tried the solution provided in this link https://github.com/isaachinman/next-i18next/issues/577#issuecomment-730497603 But still getting same error.

**Comment by omeraplak** [comment]
@Tarni-Baghel  Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
