### ISSUE TITLE
Creating a page using the CLI breaks the app

### ISSUE THREAD

**Issue by egdavid** [pankod/next-boilerplate#45]
Using the CLI to generate a page throws the following error:
```
[nodemon] starting `node app/server.js`
/home/david/Dev/site/app/routes.js:4
    .add('/a-propos', '/a-propos/index')
    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/david/Dev/site/app/server.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
[nodemon] app crashed - waiting for file changes before starting...
```
The lines in routes.js looked like this:
```
routes.add('/', '/home/index');
.add('/a-propos', '/a-propos/index')
```
Removing the semicolon solved the issue.

Edit: I guess that's an expected behavior but pages with a name that includes a dash throw errors too. That should be added to the doc since the only specified requirement is not to use "spaces".

 ```
ERROR  Failed to compile with 1 errors                                                             02:29:24

 error  in ./pages/a-propos/index.tsx

Syntax Error: SyntaxError: /home/david/Dev/site/pages/a-propos/index.tsx: Unexpected token, expected ",
" (10:11)

   8 | 
   9 | //#region Interface Imports
> 10 | import { IA-Propos } from '@Interfaces';
     |            ^
  11 | //#endregion Interface Imports
  12 | 
  13 | class A-Propos extends React.Component<IA-Propos.IProps, IA-Propos.IState> {
```

**Comment by omeraplak** [comment]
Hi @egdavid ,
Thanks for reaching us. We’re gonna investigate it. And we’ll update it soon. Feel free to contact us if you need anything.

**Comment by omeraplak** [comment]
Hi @egdavid ,
We’ve fixed template. It’s ready to use on master branch. Please do not hesitate to contact us if you need any further information.
